[browser]
gatherUsageStats = false

[client]
showErrorDetails = false

# [theme]
# primaryColor="#F25B59"

# [runner]
# enforceSerializableSessionState = true
# https://docs.streamlit.io/develop/api-reference/caching-and-state/st.session_state
